### ISSUE TITLE
Can you add #include statements

### ISSUE THREAD

**Issue by Ashwin-Paudel** [brwhale/KataScript#4]
Can you add a #include statement to the programming language. The way you can do it is by copying the contents of the file that is include, and adding the code beneath the parent file. 

If you need more help, I am happy to assist you

**Comment by brwhale** [comment]
Yeah! I'm planning on using the keyword "import". Soon we will be able to import built in modules and other script files.

Thanks for the input :P

**Comment by Ashwin-Paudel** [comment]
Ok, thanks, if you need help, just contact me.
