### ISSUE TITLE
error call member 

### ISSUE THREAD

**Issue by k1epic** [brwhale/KataScript#6]
var count = 0;

class point  
{
	var _x = 0.0;
	var _y = 0.0;
	
	func point(x,y)
	{
		count++;	
		print("|class point create|");
		_x = x;
		_y = y;
	}
	func show()
	{
		print ("point:[" , _x ,",", _y , "]");
	}
}

class Line
{
	var points = point(10.5,15.7);
	
	func Line(name, pos)
	{
	   print("|class line create|");
	}
	func display()
	{
	   points.show();  //  call child function
	}
}

line = Line("test",point(15,17));

line.display();    

//  Error at line 44: Class `point`, does not contain function `show`

**Comment by brwhale** [comment]
> ```
> var count = 0;
> 
> class point { var _x = 0.0; var _y = 0.0;
> 
> 
> func point(x,y)
> {
> 	count++;	
> 	print("|class point create|");
> 	_x = x;
> 	_y = y;
> }
> func show()
> {
> 	print ("point:[" , _x ,",", _y , "]");
> }
> 
> 
> }
> 
> class Line { var points = point(10.5,15.7);
> 
> 
> func Line(name, pos)
> {
>    print("|class line create|");
> }
> func display()
> {
>    points.show();  //  call child function
> }
> 
> 
> }
> 
> line = Line("test",point(15,17));
> 
> line.display();
> 
> // Error at line 44: Class `point`, does not contain function `show`
> ```

Hmm, thank you for reporting this, I'll dig in asap

**Comment by brwhale** [comment]
Fixed! https://github.com/brwhale/KataScript/commit/ac02c40e4cb4dfc928c53558cf307246227f53ec

Thank you for reporting this issue!

**Comment by brwhale** [comment]
Improved the fix to be more general

https://github.com/brwhale/KataScript/commit/f8a4041912108389cb4985d6ac6253b5eff05166

**Comment by k1epic** [comment]
Thanks for the quick fix
