### ISSUE TITLE
register external class or value

### ISSUE THREAD

**Issue by k1epic** [brwhale/KataScript#8]
```c++
// c++ /////////////////////////////

class myClass
{
public:
      myClass(){}
      myClass( int _a , int _b)  
     { 
       a = _a; b = _b;
     }
      int a ,b;
      void setValue( int _a , int _b) { a = _a; b = _b;}
};

// how to register my Class ? 
...

```

// KataScript  ///////////////////////////////////

var cls = myClass();
cls.setValue(5,10);
print (cls.a);

**Comment by k1epic** [comment]
attempt to register  a internal class .

// c++ /////////////////////////////

static KataScript::KataScriptInterpreter interp;

// #define BeginClass(i,name)          i.newScope(name); i.currentScope->classScope = true;
// #define AddMember(i,name,val)  i.currentScope->variables[name] = make_shared<KSValue>(KSInt(val));
// #define EndClass(i)                      i.closeCurrentScope();


  interp.newScope("myClass");
  interp.currentScope->classScope = true;
  interp.currentScope->variables["a"] =  make_shared<KSValue>(KSInt(5));
  interp.currentScope->variables["b"] =  make_shared<KSValue>(KSInt(10));

  {
      auto& newfunc = interp.newFunction("setValue", { "_a","_b" }, {});  // arg _a _b 
      interp.currentExpression = make_shared<KSExpression>(newfunc, nullptr);  // KSExpressionType::FunctionDef             
      {
          interp.currentExpression->push_back(interp.getExpression({ "a","=","_a" }));
          interp.currentExpression->push_back(interp.getExpression({ "b","=","_b" }));
      }
      interp.closeCurrentExpression();
  }


  interp.closeCurrentScope();

**Comment by k1epic** [comment]
## Error unknown exception

![Capture7](https://user-images.githubusercontent.com/7019625/163857355-a59df7ff-de67-4a81-9b48-69252f511d79.PNG)

**Comment by brwhale** [comment]
Ahh, yeah I didn't add class creation to the C++ API. I'll add that later today. Thank you for reporting these things!

**Comment by brwhale** [comment]
So I investigated this a while and realized that translating classes is not really feasible because there's not a good way to do the constructors or translate functions.

**Comment by brwhale** [comment]
Nevermind! I figured out a decent enough work around!

**Comment by brwhale** [comment]
Ok, we now have a fairly ergonomic way to create a KataScript class from C++!

added in https://github.com/brwhale/KataScript/commit/34d78e260de2c4d955e44bc89952a77a1390cf9e

stabilized in https://github.com/brwhale/KataScript/commit/d602187adc30e29957311d0bccbf816196ae0440
